name: mq3drecon
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - tqdm
  - opencv
  - cudatoolkit=11.8
  - pyyaml
  - pip
  - pip:
      - open3d==0.19.0
      - requests
      - matplotlib
